### ISSUE TITLE
Documentation: Sphinx or Mkdocs

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-fairness#20]
Now is the time to decide on the direction of documentation. Part of me is in favor of using mkdocs instead of sphinx. 

There's a few reasons. 

1. Markdown is the lingua-franka now and .rst is a bottleneck when it comes to getting folks to contribute. 
2. Mkdocs has nice customisation features and we can still make an amazing API doc. The downside is that the docstrings will need to be written in a new style. See example [here](https://rasahq.github.io/whatlies/api/embedding/) (expand the source code button).

**Comment by koaning** [comment]
@MBrouns got a strong preference here?

**Comment by MBrouns** [comment]
I like markdown quite a bit over rst so I'm all for it. You used the `mkautodocs` plugin a bit before right? If you say it's good then I'd say go for it

**Comment by koaning** [comment]
I might get started on a variant with mkdocs then.

**Comment by koaning** [comment]
Sphinx is more stable now.
